namespace Goatly.UseCases;

public sealed class CriteriaLock
{
    private readonly IReadOnlyDictionary<string, string> _fingerprints;

    private CriteriaLock(IReadOnlyDictionary<string, string> fingerprints)
    {
        _fingerprints = fingerprints;
    }

    public IReadOnlyDictionary<string, string> Entries => _fingerprints;

    public static CriteriaLock Parse(string? text)
    {
        var entries = new Dictionary<string, string>(StringComparer.Ordinal);
        if (string.IsNullOrWhiteSpace(text))
        {
            return new CriteriaLock(entries);
        }

        var content = text!;
        foreach (var rawLine in content.Replace("\r\n", "\n").Split('\n'))
        {
            var line = rawLine.Trim();
            if (line.Length == 0 || line.StartsWith("#", StringComparison.Ordinal))
            {
                continue;
            }

            var separator = line.IndexOf(' ');
            if (separator <= 0 || separator == line.Length - 1)
            {
                continue;
            }

            entries[line.Substring(0, separator)] = line.Substring(separator + 1).Trim();
        }

        return new CriteriaLock(entries);
    }

    public bool IsChanged(string key, string fingerprint) =>
        !_fingerprints.TryGetValue(key, out var locked) ||
        !string.Equals(locked, fingerprint, StringComparison.Ordinal);

    public bool Contains(string key) => _fingerprints.ContainsKey(key);

    public static string CreateSnapshot(IEnumerable<UseCasePair> pairs)
    {
        var lines = new List<string>
        {
            "# Generated by Goatly use-case tooling. Review changes before updating.",
            "# Format: <use-case-or-criterion-key> <semantic-sha256>",
            string.Empty
        };

        foreach (var pair in pairs.OrderBy(item => item.UseCase.Id, StringComparer.Ordinal))
        {
            lines.Add($"{pair.UseCase.Id} {pair.UseCase.Fingerprint}");
            lines.AddRange(pair.UseCase.Criteria
                .OrderBy(criterion => criterion.Id, StringComparer.Ordinal)
                .Select(criterion =>
                    $"{pair.UseCase.Id}/{criterion.Id} {criterion.Fingerprint}"));
        }

        return string.Join("\n", lines) + "\n";
    }
}
