using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Goatly.UseCases.Generator;

[Generator]
public sealed class GoatlyUseCaseGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor MissingUseCase = Descriptor(
        "GTLY001",
        "Missing business UseCase",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor MissingTestUse = Descriptor(
        "GTLY002",
        "Missing TestUse",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor DuplicateDocument = Descriptor(
        "GTLY003",
        "Duplicate UseCase document",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor DuplicateCriterion = Descriptor(
        "GTLY004",
        "Duplicate acceptance criterion",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor CriterionMissingFromTestUse = Descriptor(
        "GTLY005",
        "Criterion missing from TestUse",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor UnknownTestUseCriterion = Descriptor(
        "GTLY006",
        "Unknown TestUse criterion",
        DiagnosticSeverity.Error);

    private static readonly DiagnosticDescriptor ChangedDefinition = Descriptor(
        "GTLY105",
        "Use-case definition changed",
        DiagnosticSeverity.Warning);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var documents = context.AdditionalTextsProvider
            .Where(file => IsUseCaseDocument(file.Path))
            .Select((file, cancellationToken) => new InputFile(
                file.Path,
                file.GetText(cancellationToken)?.ToString() ?? string.Empty))
            .Collect();

        var lockFiles = context.AdditionalTextsProvider
            .Where(file => file.Path.EndsWith(
                "criteria.lock",
                StringComparison.OrdinalIgnoreCase))
            .Select((file, cancellationToken) =>
                file.GetText(cancellationToken)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterSourceOutput(
            documents.Combine(lockFiles),
            static (productionContext, input) => Execute(
                productionContext,
                input.Left,
                input.Right));
    }

    private static void Execute(
        SourceProductionContext context,
        IReadOnlyList<InputFile> files,
        IReadOnlyList<string> lockFiles)
    {
        var documents = files
            .Select(file => MarkdownUseCaseParser.Parse(file.Path, file.Text))
            .Where(document => document is not null)
            .Cast<UseCaseDocument>()
            .ToArray();
        var catalog = UseCaseCatalog.Create(documents);
        var criteriaLock = CriteriaLock.Parse(lockFiles.FirstOrDefault());

        foreach (var issue in catalog.Issues)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DescriptorFor(issue.Code),
                LocationAt(issue.Path, issue.Line),
                issue.Message));
        }

        foreach (var pair in catalog.Pairs.Where(pair => pair.TestUse is not null))
        {
            if (criteriaLock.IsChanged(pair.UseCase.Id, pair.UseCase.Fingerprint))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ChangedDefinition,
                    LocationAt(pair.UseCase.Path, pair.UseCase.TitleLine),
                    $"{pair.UseCase.Id} changed; review its mapped tests before acknowledging the new revision."));
            }

            foreach (var criterion in pair.UseCase.Criteria)
            {
                var key = $"{pair.UseCase.Id}/{criterion.Id}";
                if (!criteriaLock.IsChanged(key, criterion.Fingerprint))
                {
                    continue;
                }

                context.ReportDiagnostic(Diagnostic.Create(
                    ChangedDefinition,
                    LocationAt(pair.UseCase.Path, criterion.Line),
                    $"{key} changed; review every mapped test before acknowledging the new revision."));
            }
        }

        context.AddSource(
            "GoatlyCriteria.g.cs",
            SourceText.From(GenerateCriteria(documents), Encoding.UTF8));
    }

    private static string GenerateCriteria(IEnumerable<UseCaseDocument> documents)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Goatly.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class Criteria");
        builder.AppendLine("{");

        foreach (var useCase in documents
                     .Where(document => document.Kind == UseCaseDocumentKind.UseCase)
                     .GroupBy(document => document.Id, StringComparer.Ordinal)
                     .Select(group => group.First())
                     .OrderBy(document => document.Id, StringComparer.Ordinal))
        {
            builder.AppendLine($"    public sealed class {Identifier(useCase.Id)}");
            builder.AppendLine("    {");
            builder.AppendLine($"        public const string Id = {Literal(useCase.Id)};");
            builder.AppendLine($"        public const string DocumentPath = {Literal(useCase.Path)};");
            builder.AppendLine($"        public const int Line = {useCase.TitleLine};");
            builder.AppendLine($"        public const string Fingerprint = {Literal(useCase.Fingerprint)};");
            builder.AppendLine();
            builder.AppendLine($"        private {Identifier(useCase.Id)}() {{ }}");

            foreach (var criterion in useCase.Criteria
                         .GroupBy(item => item.Id, StringComparer.Ordinal)
                         .Select(group => group.First())
                         .OrderBy(item => item.Id, StringComparer.Ordinal))
            {
                builder.AppendLine();
                builder.AppendLine($"        public sealed class {Identifier(criterion.Id)}");
                builder.AppendLine("        {");
                builder.AppendLine($"            public const string UseCaseId = {Literal(useCase.Id)};");
                builder.AppendLine($"            public const string Id = {Literal(criterion.Id)};");
                builder.AppendLine($"            public const string Text = {Literal(criterion.Text)};");
                builder.AppendLine($"            public const string DocumentPath = {Literal(useCase.Path)};");
                builder.AppendLine($"            public const int Line = {criterion.Line};");
                builder.AppendLine($"            public const string Fingerprint = {Literal(criterion.Fingerprint)};");
                builder.AppendLine();
                builder.AppendLine($"            private {Identifier(criterion.Id)}() {{ }}");
                builder.AppendLine("        }");
            }

            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static bool IsUseCaseDocument(string path)
    {
        var normalized = path.Replace('\\', '/');
        return normalized.EndsWith(".md", StringComparison.OrdinalIgnoreCase) &&
               (normalized.IndexOf("/docs/use-cases/", StringComparison.OrdinalIgnoreCase) >= 0 ||
                normalized.IndexOf("/docs/testing/use-cases/", StringComparison.OrdinalIgnoreCase) >= 0);
    }

    private static DiagnosticDescriptor DescriptorFor(string code) => code switch
    {
        "GTLY001" => MissingUseCase,
        "GTLY002" => MissingTestUse,
        "GTLY003" => DuplicateDocument,
        "GTLY004" => DuplicateCriterion,
        "GTLY005" => CriterionMissingFromTestUse,
        "GTLY006" => UnknownTestUseCriterion,
        _ => ChangedDefinition
    };

    private static DiagnosticDescriptor Descriptor(
        string id,
        string title,
        DiagnosticSeverity severity) => new(
        id,
        title,
        "{0}",
        "Goatly.UseCases",
        severity,
        isEnabledByDefault: true);

    private static Location LocationAt(string path, int oneBasedLine)
    {
        var line = Math.Max(0, oneBasedLine - 1);
        return Location.Create(
            path,
            new TextSpan(0, 0),
            new LinePositionSpan(
                new LinePosition(line, 0),
                new LinePosition(line, 1)));
    }

    private static string Identifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private static string Literal(string value) =>
        "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n") + "\"";

    private sealed class InputFile
    {
        public InputFile(string path, string text)
        {
            Path = path;
            Text = text;
        }

        public string Path { get; }
        public string Text { get; }
    }
}
